version: '3'

services:

    nginx:
      build: ./requirements/Nginx/
      container_name: nginx
      restart: always
      depends_on:
        - wordpress
      ports:
        - "443:443"
      volumes:
        - /home/oabdelha/data/wp_data:/var/www/html
      networks:
        - network

    wordpress:
      build: ./requirements/WordPress
      container_name: wordpress
      restart: always
      depends_on:
        - mariadb
      ports:
        - "9000:9000"
      environment:
        ADMIN_USER: ${ADMIN_USER}
        ADMIN_EMAIL: ${ADMIN_EMAIL}
        USER_EMAIL: ${USER_EMAIL}
        URL: ${URL}
        TITLE: ${TITLE}
        WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
        WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      volumes:
        - /home/oabdelha/data/wp_data:/var/www/html
      networks: 
        - network

    mariadb:
      build: 
        context: ./requirements/MariaDB
        args:
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_DATABASE: ${MYSQL_DATABASE}
      container_name: mariadb
      restart: always
      ports:
        - "3306:3306"
      env_file:
        - .env
      volumes:
        - /home/oabdelha/data/db_data:/var/lib/mysql
      networks:
        - network

    redis:
      build: ./requirements/Bonus/Redis
      container_name: redis
      restart: always
      depends_on:
        - wordpress
      ports:
        - "6379:6379"
      networks:
        - network

    ftp-server:
      build: ./requirements/Bonus/Ftp-server
      container_name: ftp-server
      restart: always
      environment:
        FTP_USR: ${FTP_USR}
        FTP_PSW: ${FTP_PSW}
      ports:
        - "21:21"
        - "10090-10100:10090-10100"
      volumes:
        - /home/oabdelha/data/wp_data:/var/www/html
      networks:
        - network

    adminer: 
      build: ./requirements/Bonus/Adminer
      container_name: adminer
      restart: always
      depends_on:
        - mariadb
      ports:
        - "7777:7777"
      volumes:
        - /home/oabdelha/data/wp_data:/var/www/html
      networks:
        - network

    website:
      build: ./requirements/Bonus/Website
      container_name: website
      ports:
        - "9999:9999"
      depends_on:
        - wordpress
      networks:
        - network
      restart: always
      volumes:
        - /home/oabdelha/data/wp_data:/var/www/html
    
    cadvisor:
      build: ./requirements/Bonus/Cadvisor
      container_name: cadvisor
      restart: always
      ports:
        - "8080:8080"
      volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
        - /cgroup:/cgroup:ro
      privileged: true
      devices:
        - /dev/kmsg:/dev/kmsg
      networks:
        - network

networks:
  network:
    driver: bridge
