version: '3'

services:

    nginx:
      image: nginx
      build: ./requirements/Nginx/
      container_name: nginx
      restart: always
      depends_on:
        - wordpress
      ports:
        - "443:443"
      volumes:
        - wp_data:/var/www/html
      networks:
        - network_One

    wordpress:
      image: wordpress
      build: ./requirements/WordPress
      container_name: wordpress
      restart: always
      depends_on:
        - mariadb
      environment:
        ADMIN_USER: ${ADMIN_USER}
        ADMIN_EMAIL: ${ADMIN_EMAIL}
        USER_EMAIL: ${USER_EMAIL}
        URL: ${URL}
        TITLE: ${TITLE}
        WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
        WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      volumes:
        - wp_data:/var/www/html
      networks: 
        - network_One
        - network_Two

    mariadb:
      image: mariadb
      build: 
        context: ./requirements/MariaDB
        args:
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_DATABASE: ${MYSQL_DATABASE}
      container_name: mariadb
      restart: always
      volumes:
        - db_data:/var/lib/mysql
      networks:
        - network_Two

    redis:
      image: redis
      build: ./requirements/Bonus/Redis
      container_name: redis
      restart: always
      depends_on:
        - wordpress
      networks:
        - network_One

    ftp-server:
      image: ftp-server
      build: ./requirements/Bonus/Ftp-server
      container_name: ftp-server
      restart: always
      environment:
        FTP_USR: ${FTP_USR}
        FTP_PSW: ${FTP_PSW}
      ports:
        - "21:21"
        - "10090-10100:10090-10100"
      volumes:
        - wp_data:/var/www/html
      networks:
        - network_One

    adminer:
      image: adminer
      build: ./requirements/Bonus/Adminer
      container_name: adminer
      restart: always
      depends_on:
        - mariadb
      volumes:
        - wp_data:/var/www/html
      networks:
        - network_One

    website:
      image: website
      build: ./requirements/Bonus/Website
      container_name: website
      depends_on:
        - wordpress
      networks:
        - network_One
      restart: always
      volumes:
        - wp_data:/var/www/html
    
    cadvisor:
      image: cadvisor
      build: ./requirements/Bonus/Cadvisor
      container_name: cadvisor
      restart: always
      ports:
        - "8080:8080"
      volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
        - /cgroup:/cgroup:ro
      networks:
        - network_One

volumes:
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/oabdelha/data/wp_data
  
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/oabdelha/data/db_data


networks:
  network_One:
    driver: bridge
  network_Two:
    driver: bridge
