version: '3'

services:

    nginx:
      build: ./requirements/Nginx/
      container_name: nginx
      volumes:
        - wp_data:/var/www/html
      ports:
        - "443:443"
      restart: always
      depends_on:
        - wordpress

    wordpress:
      build: ./requirements/WordPress
      container_name: wordpress
      restart: always
      ports:
        - "9000:9000"
      volumes:
        - wp_data:/var/www/html
      env_file:
        - .env
      depends_on:
        - mariadb

    mariadb:
      build: 
        context: ./requirements/MariaDB
        args:
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_DATABASE: ${MYSQL_DATABASE}
      container_name: mariadb
      restart: always
      ports:
        - "3306:3306"
      volumes:
          - db_data:/var/lib/mysql
volumes:
  db_data:
  wp_data: