version: '3'

services:

    nginx:
      build: ./requirements/Nginx/
      container_name: nginx
      restart: always
      depends_on:
        - wordpress
      ports:
        - "443:443"
      volumes:
        - wp_data:/var/www/html
      networks:
        - network

    wordpress:
      build: ./requirements/WordPress
      container_name: wordpress
      restart: always
      depends_on:
        - mariadb
      ports:
        - "9000:9000"
      env_file:
        - .env
      volumes:
        - wp_data:/var/www/html
      networks: 
        - network

    mariadb:
      build: 
        context: ./requirements/MariaDB
        args:
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_DATABASE: ${MYSQL_DATABASE}
      container_name: mariadb
      restart: always
      ports:
        - "3306:3306"
      volumes:
        - db_data:/var/lib/mysql
      networks:
        - network
volumes:
  db_data:
  wp_data:

networks:
  network:
    driver: bridge
